#!/bin/busybox sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null || true

clear

/libexec/lunairos/hasinit
rm -f /libexec/lunairos/hasinit

echo "lunairos" > /proc/sys/kernel/hostname 2>/dev/null || true

exec setsid cttyhack /bin/sh
